[debug]
address = "127.0.0.1"
port = 8000
workers = 4
keep_alive = 5
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8000
workers = 16
keep_alive = 5
log_level = "critical"

[default]
secret_key = "hvYFn9IFUip3QUZTdDSCiOiLaQxgKARCQJnf1tQu97A="
template_dir = "templates"

[default.databases]
sqlite_db = { url = "database.sqlite" }

[global.databases]
sqlite_db = { url = "db.sqlite" }
